import { db } from '@/db';
import { kurdishMovies } from '@/db/schema';

async function main() {
    const sampleMovies = [
        // Original Kurdish Productions (9 movies)
        {
            tmdbId: null,
            title: 'Bajarê Min',
            titleKurdish: 'باجارێ من',
            overview: 'A heartwarming story about a young Kurdish man returning to his hometown after years abroad, discovering the changes and constants that define his identity.',
            overviewKurdish: 'چیرۆکێکی دڵگرانە دەربارەی کوڕێکی کورد کە دوای ساڵانێک لە دەرەوە دەگەڕێتەوە شارەکەی، دۆزینەوەی گۆڕانکاری و ئەو شتانەی کە ناسنامەی پێناسە دەکەن.',
            posterPath: '/kurdish_productions/bajare_min_poster.jpg',
            backdropPath: '/kurdish_productions/bajare_min_backdrop.jpg',
            releaseDate: '2023-05-15',
            voteAverage: 8.2,
            genreIds: JSON.stringify([18, 36]), // Drama, History
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/bajare-min',
            isKurdishProduction: true,
            createdAt: new Date('2023-05-15').toISOString(),
            updatedAt: new Date('2023-05-15').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Xewna Azadiyê',
            titleKurdish: 'خەونی ئازادی',
            overview: 'An epic tale of Kurdish resistance fighters during the struggle for freedom, showcasing courage, sacrifice, and the unbreakable spirit of the Kurdish people.',
            overviewKurdish: 'چیرۆکێکی ئەفسانەیی دەربارەی شەڕوانەکانی بەرگری کورد لە کاتی خەباتی ئازادیدا، پیشاندانی ورە و قوربانیدان و ڕۆحی نەشکێنراوی گەلی کورد.',
            posterPath: '/kurdish_productions/xewna_azadiye_poster.jpg',
            backdropPath: '/kurdish_productions/xewna_azadiye_backdrop.jpg',
            releaseDate: '2022-03-21',
            voteAverage: 8.7,
            genreIds: JSON.stringify([28, 18, 10752]), // Action, Drama, War
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/xewna-azadiye',
            isKurdishProduction: true,
            createdAt: new Date('2022-03-21').toISOString(),
            updatedAt: new Date('2022-03-21').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Çiyayên Kurdistan',
            titleKurdish: 'چیاکانی کوردستان',
            overview: 'A breathtaking documentary exploring the natural beauty and cultural heritage of Kurdistan\'s mountains, featuring interviews with local communities.',
            overviewKurdish: 'بەڵگەنامەیەکی سەرسوڕهێنەر کە جوانی سروشتی و میراتی کلتوری چیاکانی کوردستان دەخاتە ڕوو، لەگەڵ چاوپێکەوتن لەگەڵ کۆمەڵگا خۆجێیەکان.',
            posterPath: '/kurdish_productions/chiyakan_poster.jpg',
            backdropPath: '/kurdish_productions/chiyakan_backdrop.jpg',
            releaseDate: '2024-01-10',
            voteAverage: 7.9,
            genreIds: JSON.stringify([99]), // Documentary
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: null,
            isKurdishProduction: true,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Bûkê Kurdistanê',
            titleKurdish: 'بووکی کوردستان',
            overview: 'A romantic drama following a young Kurdish woman navigating tradition and modernity as she prepares for her wedding in contemporary Kurdistan.',
            overviewKurdish: 'درامایەکی ئاشقانە کە شوێن ژنێکی گەنج کورد دەکەوێت کە لە نێوان نەریت و نوێگەری دەڕوات لە کاتی ئامادەکردنی بۆ زەماوەندیەکەی لە کوردستانی سەردەمدا.',
            posterPath: '/kurdish_productions/buke_kurdistane_poster.jpg',
            backdropPath: '/kurdish_productions/buke_kurdistane_backdrop.jpg',
            releaseDate: '2023-08-14',
            voteAverage: 7.5,
            genreIds: JSON.stringify([10749, 18]), // Romance, Drama
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/buke-kurdistane',
            isKurdishProduction: true,
            createdAt: new Date('2023-08-14').toISOString(),
            updatedAt: new Date('2023-08-14').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Dengê Bilbil',
            titleKurdish: 'دەنگی بڵبڵ',
            overview: 'A musical drama about a young Kurdish singer trying to preserve traditional Kurdish music while finding his place in the modern world.',
            overviewKurdish: 'درامایەکی مۆسیقی دەربارەی گۆرانیبێژێکی گەنج کورد کە هەوڵ دەدات مۆسیقا نەریتییەکانی کورد بپارێزێت لە کاتێکدا شوێنی خۆی لە جیهانی سەردەمدا دەدۆزێتەوە.',
            posterPath: '/kurdish_productions/denge_bilbil_poster.jpg',
            backdropPath: '/kurdish_productions/denge_bilbil_backdrop.jpg',
            releaseDate: '2021-11-25',
            voteAverage: 8.1,
            genreIds: JSON.stringify([10402, 18]), // Music, Drama
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/denge-bilbil',
            isKurdishProduction: true,
            createdAt: new Date('2021-11-25').toISOString(),
            updatedAt: new Date('2021-11-25').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Rojhilat',
            titleKurdish: 'ڕۆژهەڵات',
            overview: 'An adventure film following a group of young Kurds on a journey across the Kurdistan region, discovering friendship and their cultural roots.',
            overviewKurdish: 'فیلمێکی سەرگەرمی کە شوێن گروپێک لە گەنجانی کورد دەکەوێت لە گەشتێکدا بە هەرێمی کوردستاندا، دۆزینەوەی هاوڕێیەتی و ڕەگەزەکانی کلتوریان.',
            posterPath: '/kurdish_productions/rojhilat_poster.jpg',
            backdropPath: '/kurdish_productions/rojhilat_backdrop.jpg',
            releaseDate: '2024-06-20',
            voteAverage: 7.3,
            genreIds: JSON.stringify([12, 18]), // Adventure, Drama
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: null,
            isKurdishProduction: true,
            createdAt: new Date('2024-06-20').toISOString(),
            updatedAt: new Date('2024-06-20').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Komîdyaya Bazarê',
            titleKurdish: 'کۆمیدیای بازاڕ',
            overview: 'A hilarious comedy about the everyday adventures of vendors and customers in a traditional Kurdish bazaar, full of wit and cultural humor.',
            overviewKurdish: 'کۆمیدیایەکی پێکەنیناوی دەربارەی سەرگەرمییە ڕۆژانەکانی فرۆشیار و کڕیارەکان لە بازاڕێکی نەریتی کوردیدا، پڕ لە تێگەیشتن و گاڵتەجاڕی کلتوری.',
            posterPath: '/kurdish_productions/komidya_bazar_poster.jpg',
            backdropPath: '/kurdish_productions/komidya_bazar_backdrop.jpg',
            releaseDate: '2023-12-08',
            voteAverage: 6.8,
            genreIds: JSON.stringify([35]), // Comedy
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/komidya-bazar',
            isKurdishProduction: true,
            createdAt: new Date('2023-12-08').toISOString(),
            updatedAt: new Date('2023-12-08').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Şerê Dawî',
            titleKurdish: 'شەڕی دوایی',
            overview: 'An intense war drama depicting the final battles of Kurdish peshmerga forces, showcasing heroism and the cost of freedom.',
            overviewKurdish: 'درامایەکی توند دەربارەی شەڕە دواییەکانی هێزەکانی پێشمەرگەی کورد، پیشاندانی پاڵەوانیەتی و نرخی ئازادی.',
            posterPath: '/kurdish_productions/shere_dayi_poster.jpg',
            backdropPath: '/kurdish_productions/shere_dayi_backdrop.jpg',
            releaseDate: '2020-09-12',
            voteAverage: 8.4,
            genreIds: JSON.stringify([28, 18, 10752]), // Action, Drama, War
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/shere-dayi',
            isKurdishProduction: true,
            createdAt: new Date('2020-09-12').toISOString(),
            updatedAt: new Date('2020-09-12').toISOString(),
        },
        {
            tmdbId: null,
            title: 'Hînî Kurd',
            titleKurdish: 'هێنی کورد',
            overview: 'A touching family drama about a Kurdish teacher dedicated to preserving the Kurdish language and educating the next generation.',
            overviewKurdish: 'درامایەکی خێزانی دڵسۆزانە دەربارەی مامۆستایەکی کورد کە خۆی تەرخان کردووە بۆ پاراستنی زمانی کوردی و پەروەردەکردنی نەوەی داهاتوو.',
            posterPath: '/kurdish_productions/hini_kurd_poster.jpg',
            backdropPath: '/kurdish_productions/hini_kurd_backdrop.jpg',
            releaseDate: '2022-10-05',
            voteAverage: 7.7,
            genreIds: JSON.stringify([18, 10751]), // Drama, Family
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: null,
            isKurdishProduction: true,
            createdAt: new Date('2022-10-05').toISOString(),
            updatedAt: new Date('2022-10-05').toISOString(),
        },

        // International Movies with Kurdish Dubbing/Subtitles (16 movies)
        {
            tmdbId: 550,
            title: 'Fight Club',
            titleKurdish: 'کلووبی شەڕ',
            overview: 'An insomniac office worker and a devil-may-care soapmaker form an underground fight club.',
            overviewKurdish: 'کارمەندێکی نەخۆش و دروستکەرێکی سابوون کلووبێکی شەڕی ژێرزەوی دامەزرێنن.',
            posterPath: '/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg',
            backdropPath: '/hZkgoQYus5vegHoetLkCJzb17zJ.jpg',
            releaseDate: '1999-10-15',
            voteAverage: 8.4,
            genreIds: JSON.stringify([18, 53]), // Drama, Thriller
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'good',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/fight-club',
            isKurdishProduction: false,
            createdAt: new Date('2020-01-15').toISOString(),
            updatedAt: new Date('2020-01-15').toISOString(),
        },
        {
            tmdbId: 238,
            title: 'The Shawshank Redemption',
            titleKurdish: 'کۆڵبەرییەکەی شاوشانک',
            overview: 'Two imprisoned men bond over years, finding solace and eventual redemption.',
            overviewKurdish: 'دوو پیاوی زیندانی پەیوەندی لە ماوەی ساڵانێکدا، دۆزینەوەی ئارامی و کۆتایی کۆڵبەری.',
            posterPath: '/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg',
            backdropPath: '/j9XKiZrVeViAixVRzCta7h1VU9W.jpg',
            releaseDate: '1994-09-23',
            voteAverage: 9.0,
            genreIds: JSON.stringify([18, 80]), // Drama, Crime
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            kurdishDubQuality: null,
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/shawshank-redemption',
            isKurdishProduction: false,
            createdAt: new Date('2019-05-20').toISOString(),
            updatedAt: new Date('2019-05-20').toISOString(),
        },
        {
            tmdbId: 155,
            title: 'The Dark Knight',
            titleKurdish: 'شەوانە تاریکەکە',
            overview: 'Batman faces the Joker in a battle for Gotham\'s soul.',
            overviewKurdish: 'باتمان ڕووبەڕووی جۆکەر دەبێتەوە لە شەڕێکدا بۆ گیانی گۆسام.',
            posterPath: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
            backdropPath: '/hqkIcbrOHL86UncnHIsHVcVmzue.jpg',
            releaseDate: '2008-07-18',
            voteAverage: 8.8,
            genreIds: JSON.stringify([28, 80, 18]), // Action, Crime, Drama
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'good',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: null,
            isKurdishProduction: false,
            createdAt: new Date('2018-07-18').toISOString(),
            updatedAt: new Date('2018-07-18').toISOString(),
        },
        {
            tmdbId: 13,
            title: 'Forrest Gump',
            titleKurdish: 'فۆڕست گامپ',
            overview: 'The presidencies of Kennedy and Johnson through the eyes of an Alabama man.',
            overviewKurdish: 'سەرۆکایەتی کەنەدی و جۆنسن لە ڕێگەی چاوی پیاوێکی ئەلابامەوە.',
            posterPath: '/arw2vcBveWOVZr6pxd9XTd1TdQa.jpg',
            backdropPath: '/3h1JZGDhZ8nzxdgvkxha0qBqi05.jpg',
            releaseDate: '1994-06-23',
            voteAverage: 8.5,
            genreIds: JSON.stringify([18, 10749]), // Drama, Romance
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'fair',
            kurdishSubtitleQuality: 'good',
            streamingUrl: 'https://kurdstream.com/watch/forrest-gump',
            isKurdishProduction: false,
            createdAt: new Date('2019-12-10').toISOString(),
            updatedAt: new Date('2019-12-10').toISOString(),
        },
        {
            tmdbId: 680,
            title: 'Pulp Fiction',
            titleKurdish: 'پەلپ فیکشن',
            overview: 'The lives of two mob hitmen, a boxer, and a gangster intertwine.',
            overviewKurdish: 'ژیانی دوو کوژەری مافیا، بۆکسەرێک و گانگستەرێک تێکەڵ دەبن.',
            posterPath: '/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
            backdropPath: '/4cDFJr4HnXN5AbF5kjjrmaKWQ5z.jpg',
            releaseDate: '1994-09-10',
            voteAverage: 8.3,
            genreIds: JSON.stringify([80, 18]), // Crime, Drama
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            kurdishDubQuality: null,
            kurdishSubtitleQuality: 'good',
            streamingUrl: null,
            isKurdishProduction: false,
            createdAt: new Date('2020-03-15').toISOString(),
            updatedAt: new Date('2020-03-15').toISOString(),
        },
        {
            tmdbId: 122,
            title: 'The Lord of the Rings: The Return of the King',
            titleKurdish: 'گەورەی ئەڵقەکان: گەڕانەوەی پاشا',
            overview: 'Gandalf and Aragorn lead the World of Men against Sauron\'s army.',
            overviewKurdish: 'گاندالف و ئاراگۆرن جیهانی مرۆڤەکان بەرامبەر بە سوپای ساورۆن ڕابەرایەتی دەکەن.',
            posterPath: '/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg',
            backdropPath: '/8BPZO0Bf8TeAy8znF43z8soK3ys.jpg',
            releaseDate: '2003-12-01',
            voteAverage: 8.7,
            genreIds: JSON.stringify([12, 18, 14]), // Adventure, Drama, Fantasy
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/lotr-return-king',
            isKurdishProduction: false,
            createdAt: new Date('2017-11-20').toISOString(),
            updatedAt: new Date('2017-11-20').toISOString(),
        },
        {
            tmdbId: 769,
            title: 'GoodFellas',
            titleKurdish: 'کابرایەتی باشەکان',
            overview: 'The story of Henry Hill and his life in the mob.',
            overviewKurdish: 'چیرۆکی هێنری هیل و ژیانی لە مافیادا.',
            posterPath: '/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg',
            backdropPath: '/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg',
            releaseDate: '1990-09-12',
            voteAverage: 8.2,
            genreIds: JSON.stringify([18, 80]), // Drama, Crime
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            kurdishDubQuality: null,
            kurdishSubtitleQuality: 'fair',
            streamingUrl: 'https://kurdstream.com/watch/goodfellas',
            isKurdishProduction: false,
            createdAt: new Date('2021-04-08').toISOString(),
            updatedAt: new Date('2021-04-08').toISOString(),
        },
        {
            tmdbId: 389,
            title: '12 Angry Men',
            titleKurdish: '١٢ پیاوی تووڕە',
            overview: 'A jury holdout attempts to prevent a miscarriage of justice.',
            overviewKurdish: 'ئەندامێکی ژووری هەوڵ دەدات ڕێگری لە هەڵەی دادوەری بکات.',
            posterPath: '/ppd84D2i9W8jXmsyInGyihiSyqz.jpg',
            backdropPath: '/A7YPhQKdgch6xndfRUWZu8STBE.jpg',
            releaseDate: '1957-04-10',
            voteAverage: 8.9,
            genreIds: JSON.stringify([18]), // Drama
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'poor',
            kurdishSubtitleQuality: 'good',
            streamingUrl: null,
            isKurdishProduction: false,
            createdAt: new Date('2022-08-30').toISOString(),
            updatedAt: new Date('2022-08-30').toISOString(),
        },
        {
            tmdbId: 19404,
            title: 'Dilwale Dulhania Le Jayenge',
            titleKurdish: 'دڵی ئاشق کچ دەبات',
            overview: 'A young couple falls in love during a trip to Europe.',
            overviewKurdish: 'جووتێکی گەنج لە کاتی گەشتێک بۆ ئەوروپا عاشق دەبن.',
            posterPath: '/2CAL2433ZeIihfX1Hb2139CX0pW.jpg',
            backdropPath: '/90ez6ArvpO8bvpyIngBuwXOqJm5.jpg',
            releaseDate: '1995-10-20',
            voteAverage: 8.1,
            genreIds: JSON.stringify([35, 18, 10749]), // Comedy, Drama, Romance
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'good',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/ddlj',
            isKurdishProduction: false,
            createdAt: new Date('2023-02-14').toISOString(),
            updatedAt: new Date('2023-02-14').toISOString(),
        },
        {
            tmdbId: 496243,
            title: 'Parasite',
            titleKurdish: 'پارازیت',
            overview: 'A poor family schemes to become employed by a wealthy family.',
            overviewKurdish: 'خێزانێکی هەژار پیلان دادەڕێژن بۆ کارکردن لەلای خێزانێکی دەوڵەمەند.',
            posterPath: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
            backdropPath: '/TU9NIjwzjoKPwQHoHshkBcQZzr.jpg',
            releaseDate: '2019-05-30',
            voteAverage: 8.0,
            genreIds: JSON.stringify([35, 53, 18]), // Comedy, Thriller, Drama
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            kurdishDubQuality: null,
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/parasite',
            isKurdishProduction: false,
            createdAt: new Date('2020-11-05').toISOString(),
            updatedAt: new Date('2020-11-05').toISOString(),
        },
        {
            tmdbId: 429617,
            title: 'Spider-Man: Into the Spider-Verse',
            titleKurdish: 'جاڵجاڵۆکە مرۆڤ: چوونە ناو جیهانی جاڵجاڵۆکەکان',
            overview: 'Teen Miles Morales becomes Spider-Man of his reality.',
            overviewKurdish: 'گەنجە مایڵس مۆرالیس دەبێتە جاڵجاڵۆکە مرۆڤی ڕاستییەکەی.',
            posterPath: '/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg',
            backdropPath: '/7d6EY00g1c39SGZOoCJ5Py9nNth.jpg',
            releaseDate: '2018-12-01',
            voteAverage: 7.9,
            genreIds: JSON.stringify([16, 28, 12]), // Animation, Action, Adventure
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'good',
            kurdishSubtitleQuality: 'good',
            streamingUrl: null,
            isKurdishProduction: false,
            createdAt: new Date('2019-03-18').toISOString(),
            updatedAt: new Date('2019-03-18').toISOString(),
        },
        {
            tmdbId: 278,
            title: 'The Godfather',
            titleKurdish: 'باوکی خودا',
            overview: 'The aging patriarch transfers control of his crime empire to his son.',
            overviewKurdish: 'پیرەمێردە سەرۆکەکە کۆنترۆڵی ئیمپراتۆریەتی تاوانکارییەکەی دەگوازێتەوە بۆ کوڕەکەی.',
            posterPath: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
            backdropPath: '/tmU7GeKVybMWFButWEGl2M4GeiP.jpg',
            releaseDate: '1972-03-14',
            voteAverage: 8.6,
            genreIds: JSON.stringify([18, 80]), // Drama, Crime
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/godfather',
            isKurdishProduction: false,
            createdAt: new Date('2016-08-22').toISOString(),
            updatedAt: new Date('2016-08-22').toISOString(),
        },
        {
            tmdbId: 324857,
            title: 'Spider-Man: Into the Spider-Verse',
            titleKurdish: 'شازادەی شیرەکە',
            overview: 'A lion prince flees his kingdom only to learn the true meaning of responsibility.',
            overviewKurdish: 'شازادەی شێرێک لە پاشایەتییەکەی هەڵاتووە تەنها بۆ فێربوونی واتای ڕاستەقینەی بەرپرسیارێتی.',
            posterPath: '/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg',
            backdropPath: '/1TUg5pO1VZ4B0Q1amNXnc4UBSGL.jpg',
            releaseDate: '2019-07-12',
            voteAverage: 7.1,
            genreIds: JSON.stringify([12, 16, 18, 10751, 10402]), // Adventure, Animation, Drama, Family, Music
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'excellent',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/lion-king',
            isKurdishProduction: false,
            createdAt: new Date('2019-09-15').toISOString(),
            updatedAt: new Date('2019-09-15').toISOString(),
        },
        {
            tmdbId: 27205,
            title: 'Inception',
            titleKurdish: 'دەستپێک',
            overview: 'A thief who steals corporate secrets through dream-sharing technology.',
            overviewKurdish: 'دزێک کە نهێنییەکانی کۆمپانیا لە ڕێگەی تەکنەلۆژیای هاوبەشکردنی خەونەوە دەدزێت.',
            posterPath: '/9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg',
            backdropPath: '/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
            releaseDate: '2010-07-15',
            voteAverage: 8.1,
            genreIds: JSON.stringify([28, 878, 53]), // Action, Sci-Fi, Thriller
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            kurdishDubQuality: null,
            kurdishSubtitleQuality: 'good',
            streamingUrl: null,
            isKurdishProduction: false,
            createdAt: new Date('2021-07-28').toISOString(),
            updatedAt: new Date('2021-07-28').toISOString(),
        },
        {
            tmdbId: 372058,
            title: 'Your Name',
            titleKurdish: 'ناوی تۆ',
            overview: 'Two teenagers share a profound, magical connection upon discovering they are swapping bodies.',
            overviewKurdish: 'دوو گەنج پەیوەندییەکی قووڵ و سیحراوی هەیە کاتێک دەزانن کە جەستەکانیان دەگۆڕن.',
            posterPath: '/q719jXXEzOoYaps6babgKnONONX.jpg',
            backdropPath: '/F6KZTzCfGh8Bxq571yedHfdd21S.jpg',
            releaseDate: '2016-08-26',
            voteAverage: 8.2,
            genreIds: JSON.stringify([16, 18, 10749]), // Animation, Drama, Romance
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'fair',
            kurdishSubtitleQuality: 'excellent',
            streamingUrl: 'https://kurdstream.com/watch/your-name',
            isKurdishProduction: false,
            createdAt: new Date('2017-04-12').toISOString(),
            updatedAt: new Date('2017-04-12').toISOString(),
        },
        {
            tmdbId: 533535,
            title: 'Deadpool & Wolverine',
            titleKurdish: 'دێدپوول و ولڤەرین',
            overview: 'Deadpool teams up with Wolverine in an epic adventure across the multiverse.',
            overviewKurdish: 'دێدپوول لەگەڵ ولڤەرین یەکدەگرن لە سەرگەرمییەکی ئەفسانەیی بە چەندین جیهاندا.',
            posterPath: '/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
            backdropPath: '/yDHYTfA3R0jFYba4szg2v7fPdab.jpg',
            releaseDate: '2024-07-24',
            voteAverage: 7.8,
            genreIds: JSON.stringify([28, 35, 878]), // Action, Comedy, Sci-Fi
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            kurdishDubQuality: 'good',
            kurdishSubtitleQuality: 'good',
            streamingUrl: 'https://kurdstream.com/watch/deadpool-wolverine',
            isKurdishProduction: false,
            createdAt: new Date('2024-08-15').toISOString(),
            updatedAt: new Date('2024-08-15').toISOString(),
        }
    ];

    await db.insert(kurdishMovies).values(sampleMovies);
    
    console.log('✅ Kurdish movies seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});