import { db } from '@/db';
import { movieAnalytics } from '@/db/schema';

async function main() {
    const sampleMovieAnalytics = [
        // TMDB Movies
        {
            movieId: 155,
            movieType: 'tmdb',
            totalViews: 2847,
            totalReviews: 4,
            averageRating: 8.7,
            totalFavorites: 78,
            totalWatchTime: 487320,
            popularityScore: 857.9,
            trendingScore: 943.69,
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            movieId: 238,
            movieType: 'tmdb',
            totalViews: 4230,
            totalReviews: 5,
            averageRating: 9.2,
            totalFavorites: 95,
            totalWatchTime: 723600,
            popularityScore: 1280.3,
            trendingScore: 1152.27,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-02-20').toISOString(),
        },
        {
            movieId: 550,
            movieType: 'tmdb',
            totalViews: 3856,
            totalReviews: 4,
            averageRating: 8.9,
            totalFavorites: 87,
            totalWatchTime: 658240,
            popularityScore: 1166.5,
            trendingScore: 1049.85,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-02-25').toISOString(),
        },
        {
            movieId: 13,
            movieType: 'tmdb',
            totalViews: 1923,
            totalReviews: 3,
            averageRating: 7.8,
            totalFavorites: 45,
            totalWatchTime: 328920,
            popularityScore: 584.4,
            trendingScore: 525.96,
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            movieId: 680,
            movieType: 'tmdb',
            totalViews: 3421,
            totalReviews: 3,
            averageRating: 8.5,
            totalFavorites: 72,
            totalWatchTime: 584760,
            popularityScore: 1033.6,
            trendingScore: 1136.96,
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            movieId: 122,
            movieType: 'tmdb',
            totalViews: 2764,
            totalReviews: 2,
            averageRating: 7.9,
            totalFavorites: 58,
            totalWatchTime: 472680,
            popularityScore: 838.0,
            trendingScore: 754.2,
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            movieId: 278,
            movieType: 'tmdb',
            totalViews: 4892,
            totalReviews: 5,
            averageRating: 9.3,
            totalFavorites: 98,
            totalWatchTime: 835440,
            popularityScore: 1487.4,
            trendingScore: 1339.66,
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            movieId: 27205,
            movieType: 'tmdb',
            totalViews: 1567,
            totalReviews: 2,
            averageRating: 7.4,
            totalFavorites: 38,
            totalWatchTime: 267940,
            popularityScore: 475.9,
            trendingScore: 523.49,
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        },
        {
            movieId: 603,
            movieType: 'tmdb',
            totalViews: 3145,
            totalReviews: 4,
            averageRating: 8.6,
            totalFavorites: 67,
            totalWatchTime: 537660,
            popularityScore: 950.2,
            trendingScore: 855.18,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-02-22').toISOString(),
        },
        {
            movieId: 299534,
            movieType: 'tmdb',
            totalViews: 4658,
            totalReviews: 4,
            averageRating: 8.8,
            totalFavorites: 89,
            totalWatchTime: 796920,
            popularityScore: 1415.3,
            trendingScore: 1273.77,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        // Kurdish Movies
        {
            movieId: 1,
            movieType: 'kurdish',
            totalViews: 892,
            totalReviews: 3,
            averageRating: 7.2,
            totalFavorites: 23,
            totalWatchTime: 152520,
            popularityScore: 271.9,
            trendingScore: 299.09,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-28').toISOString(),
        },
        {
            movieId: 2,
            movieType: 'kurdish',
            totalViews: 1234,
            totalReviews: 4,
            averageRating: 8.1,
            totalFavorites: 45,
            totalWatchTime: 211020,
            totalWatchTime: 211020,
            popularityScore: 374.3,
            trendingScore: 411.73,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-03-01').toISOString(),
        },
        {
            movieId: 3,
            movieType: 'kurdish',
            totalViews: 756,
            totalReviews: 2,
            averageRating: 6.8,
            totalFavorites: 18,
            totalWatchTime: 129240,
            popularityScore: 230.6,
            trendingScore: 253.66,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-03-03').toISOString(),
        },
        {
            movieId: 4,
            movieType: 'kurdish',
            totalViews: 1567,
            totalReviews: 5,
            averageRating: 8.5,
            totalFavorites: 62,
            totalWatchTime: 268020,
            popularityScore: 477.3,
            trendingScore: 525.03,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-03-05').toISOString(),
        },
        {
            movieId: 5,
            movieType: 'kurdish',
            totalViews: 689,
            totalReviews: 2,
            averageRating: 7.0,
            totalFavorites: 15,
            totalWatchTime: 117780,
            popularityScore: 210.2,
            trendingScore: 189.18,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-03-08').toISOString(),
        },
        {
            movieId: 6,
            movieType: 'kurdish',
            totalViews: 1098,
            totalReviews: 3,
            averageRating: 7.6,
            totalFavorites: 34,
            totalWatchTime: 187740,
            popularityScore: 334.8,
            trendingScore: 368.28,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-03-10').toISOString(),
        },
        {
            movieId: 7,
            movieType: 'kurdish',
            totalViews: 456,
            totalReviews: 1,
            averageRating: 6.5,
            totalFavorites: 12,
            totalWatchTime: 77980,
            popularityScore: 139.6,
            trendingScore: 153.56,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-03-12').toISOString(),
        },
        {
            movieId: 8,
            movieType: 'kurdish',
            totalViews: 823,
            totalReviews: 2,
            averageRating: 7.3,
            totalFavorites: 28,
            totalWatchTime: 140740,
            popularityScore: 251.5,
            trendingScore: 276.65,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        // Coming Soon Movies
        {
            movieId: 999,
            movieType: 'coming_soon',
            totalViews: 234,
            totalReviews: 1,
            averageRating: 6.0,
            totalFavorites: 8,
            totalWatchTime: 0,
            popularityScore: 71.4,
            trendingScore: 78.54,
            createdAt: new Date('2024-03-01').toISOString(),
            updatedAt: new Date('2024-03-15').toISOString(),
        },
        {
            movieId: 1000,
            movieType: 'coming_soon',
            totalViews: 567,
            totalReviews: 2,
            averageRating: 7.5,
            totalFavorites: 19,
            totalWatchTime: 0,
            popularityScore: 173.0,
            trendingScore: 190.3,
            createdAt: new Date('2024-03-05').toISOString(),
            updatedAt: new Date('2024-03-18').toISOString(),
        },
    ];

    await db.insert(movieAnalytics).values(sampleMovieAnalytics);
    
    console.log('✅ Movie analytics seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});