import { db } from '@/db';
import { movieReviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 155,
            movieType: 'tmdb',
            title: 'A Masterpiece of Cinema',
            content: 'The Dark Knight stands as one of the greatest superhero films ever made. Christopher Nolan masterfully crafts a psychological thriller that transcends the comic book genre. Heath Ledger delivers a haunting, career-defining performance as the Joker, bringing an unpredictable chaos that keeps you on edge throughout. The film explores themes of morality, justice, and the fine line between heroism and vigilantism. The cinematography is stunning, particularly the IMAX sequences, and Hans Zimmer score perfectly complements the dark tone. Christian Bale brings depth to Batman, showing the emotional toll of being Gotham protector. This is more than a superhero movie - it is a complex study of human nature.',
            rating: 10,
            isComingSoon: false,
            helpful: 45,
            spoilerWarning: false,
            createdAt: new Date('2024-06-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-06-15T14:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 550,
            movieType: 'tmdb',
            title: 'Mind-Bending Brilliance',
            content: 'Fight Club is a revolutionary film that challenges societal norms and consumer culture with brutal honesty. David Fincher direction is meticulous, creating a grimy, urban atmosphere that perfectly reflects the protagonist dissatisfaction with modern life. Edward Norton delivers an excellent performance as the unnamed narrator, while Brad Pitt is charismatic and dangerous as Tyler Durden. The film psychological depth is incredible, building to a twist that recontextualizes everything you have seen. The critique of masculinity, capitalism, and conformity remains relevant today. The cinematography and editing are top-notch, with creative visual techniques that enhance the storytelling. This is intelligent cinema that rewards multiple viewings.',
            rating: 9,
            isComingSoon: false,
            helpful: 38,
            spoilerWarning: true,
            createdAt: new Date('2024-07-02T19:45:00Z').toISOString(),
            updatedAt: new Date('2024-07-02T19:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 27205,
            movieType: 'tmdb',
            title: 'Dream Within a Dream',
            content: 'Inception is Christopher Nolan at his most ambitious, creating a complex heist film set within the architecture of dreams. Leonardo DiCaprio gives a powerful performance as Dom Cobb, a man haunted by guilt and longing for redemption. The film layered narrative structure is ingenious, with multiple dream levels that create increasing stakes and tension. The practical effects and cinematography are extraordinary, particularly the rotating hallway fight scene and the folding Paris sequence. Marion Cotillard is haunting as Mal, representing both love and destruction. The ensemble cast, including Tom Hardy and Michael Caine, delivers strong performances throughout. While the plot can be complex, the emotional core of a father wanting to return to his children grounds the high-concept premise.',
            rating: 9,
            isComingSoon: false,
            helpful: 42,
            spoilerWarning: false,
            createdAt: new Date('2024-07-20T11:15:00Z').toISOString(),
            updatedAt: new Date('2024-07-20T11:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 238,
            movieType: 'tmdb',
            title: 'Timeless Tale of Hope',
            content: 'The Shawshank Redemption is a profoundly moving story about friendship, hope, and redemption. Tim Robbins and Morgan Freeman have incredible chemistry, making their friendship the heart of the film. The story of Andy Dufresne journey through Shawshank prison is both heartbreaking and inspiring. Frank Darabont direction is careful and respectful, allowing the characters to breathe and develop naturally. The cinematography beautifully captures both the claustrophobia of prison life and the expansive hope that Andy represents. Thomas Newman score is subtle yet powerful, enhancing the emotional moments without overwhelming them. The film message about maintaining dignity and hope in the darkest circumstances is universal and timeless. Every performance is pitch-perfect, creating a deeply human story.',
            rating: 10,
            isComingSoon: false,
            helpful: 50,
            spoilerWarning: false,
            createdAt: new Date('2024-08-05T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-08-05T16:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 680,
            movieType: 'tmdb',
            title: 'Pulp Fiction: Genre-Defining Classic',
            content: 'Quentin Tarantino Pulp Fiction revolutionized cinema with its non-linear narrative and sharp dialogue. The interconnected stories of hitmen, boxers, and gangsters create a rich tapestry of Los Angeles underworld. John Travolta and Samuel L. Jackson have electric chemistry as Vincent and Jules, delivering some of the most quotable lines in film history. Uma Thurman is captivating as Mia Wallace, particularly in the iconic dance scene with Travolta. The film pop culture references and eclectic soundtrack create a unique atmosphere that influenced countless filmmakers. Tarantino writing is razor-sharp, mixing dark humor with sudden violence. The cinematography and editing create a stylized world that feels both realistic and heightened. This is essential viewing for any serious film enthusiast.',
            rating: 8,
            isComingSoon: false,
            helpful: 35,
            spoilerWarning: false,
            createdAt: new Date('2024-08-18T13:40:00Z').toISOString(),
            updatedAt: new Date('2024-08-18T13:40:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 13,
            movieType: 'tmdb',
            title: 'Scorsese Crime Epic',
            content: 'Forrest Gump is a heartwarming journey through American history seen through the eyes of an extraordinary ordinary man. Tom Hanks delivers one of his finest performances, bringing innocence and wisdom to the character of Forrest. The film seamlessly weaves historical events into personal story, creating both entertainment and commentary on American culture. The visual effects that insert Forrest into historical footage are impressive and well-integrated. Robin Wright is excellent as Jenny, portraying a complex character struggling with her demons. The film explores themes of destiny, love, and perseverance with gentle humor and genuine emotion. While some may find it sentimental, the film sincerity and Hanks performance make it genuinely moving. The soundtrack perfectly captures the different eras the film spans.',
            rating: 8,
            isComingSoon: false,
            helpful: 29,
            spoilerWarning: false,
            createdAt: new Date('2024-09-01T10:25:00Z').toISOString(),
            updatedAt: new Date('2024-09-01T10:25:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 278,
            movieType: 'tmdb',
            title: 'Space Opera Spectacle',
            content: 'The Matrix redefined science fiction cinema with its groundbreaking action sequences and philosophical depth. Keanu Reeves is perfectly cast as Neo, bringing the right blend of confusion and determination to the chosen one role. The Wachowski sisters created a visual language that influenced action filmmaking for decades. The bullet-time effects were revolutionary, but the film succeeds because of its deeper questions about reality and free will. Laurence Fishburne brings gravitas to Morpheus, while Carrie-Anne Moss is excellent as Trinity. The production design creates a believable dystopian world, contrasting the sterile Matrix with the gritty reality of Zion. The philosophical themes about simulation, choice, and awakening remain relevant in our digital age. This is both spectacular entertainment and thoughtful science fiction.',
            rating: 8,
            isComingSoon: false,
            helpful: 41,
            spoilerWarning: false,
            createdAt: new Date('2024-09-15T15:55:00Z').toISOString(),
            updatedAt: new Date('2024-09-15T15:55:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 122,
            movieType: 'tmdb',
            title: 'Tolkien Vision Realized',
            content: 'The Lord of the Rings trilogy represents the pinnacle of fantasy filmmaking, but Fellowship sets the stage beautifully. Peter Jackson captures the epic scope of Middle-earth while maintaining the intimate character moments that make Tolkien work special. The cast is perfectly chosen, with Ian McKellen bringing gravitas to Gandalf and Elijah Wood capturing Frodo innocence and determination. The practical effects and locations create a believable fantasy world that feels lived-in and real. Howard Shore score is majestic, enhancing every moment without overwhelming the story. The film balances action, humor, and emotion expertly, making the three-hour runtime feel necessary rather than excessive. The attention to detail in costumes, makeup, and set design is extraordinary. This is how you adapt beloved source material with respect and creativity.',
            rating: 7,
            isComingSoon: false,
            helpful: 33,
            spoilerWarning: false,
            createdAt: new Date('2024-10-02T12:10:00Z').toISOString(),
            updatedAt: new Date('2024-10-02T12:10:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 3,
            movieType: 'kurdish',
            title: 'Powerful Kurdish Drama',
            content: 'This Kurdish film delivers an emotionally resonant story about family, tradition, and the struggle between old and new ways of life. The cinematography beautifully captures the Kurdish landscape, making the setting almost a character in itself. The lead performance is particularly strong, conveying deep emotion through subtle expressions and body language. The film explores themes of identity and belonging with nuance and sensitivity. The use of traditional Kurdish music throughout enhances the cultural authenticity and emotional impact. While some pacing issues slow down the middle act, the powerful climax makes the journey worthwhile. The dialogue feels natural and unforced, allowing the characters to develop organically. This is an important contribution to Kurdish cinema that deserves wider recognition.',
            rating: 7,
            isComingSoon: false,
            helpful: 18,
            spoilerWarning: false,
            createdAt: new Date('2024-06-28T14:35:00Z').toISOString(),
            updatedAt: new Date('2024-06-28T14:35:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 7,
            movieType: 'kurdish',
            title: 'Authentic Cultural Story',
            content: 'A beautifully crafted film that showcases Kurdish culture and traditions through compelling storytelling. The director demonstrates a deep understanding of Kurdish life, creating scenes that feel authentic and lived-in. The ensemble cast delivers naturalistic performances that bring the community to life. The film tackles serious social issues while maintaining hope and humanity throughout. The cinematography makes excellent use of natural lighting and real locations, creating visual poetry that supports the narrative. Traditional Kurdish customs are woven naturally into the story without feeling forced or explanatory. The pacing allows for character development and emotional moments to breathe. While the film may be challenging for international audiences unfamiliar with Kurdish culture, it rewards patient viewing with genuine insight and emotional truth.',
            rating: 6,
            isComingSoon: false,
            helpful: 14,
            spoilerWarning: false,
            createdAt: new Date('2024-07-12T18:20:00Z').toISOString(),
            updatedAt: new Date('2024-07-12T18:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 1,
            movieType: 'kurdish',
            title: 'Promising but Flawed',
            content: 'This Kurdish production shows ambition and cultural pride but struggles with technical execution and pacing issues. The story has potential, dealing with contemporary Kurdish life and generational conflicts, but the script feels underdeveloped in places. Some performances are strong, particularly from the veteran actors, while younger cast members seem less comfortable on camera. The production values are inconsistent - some scenes are beautifully shot while others feel rushed or poorly lit. The film heart is in the right place, addressing important themes about identity and community, but the execution does not always match the ambition. The dialogue sometimes feels stilted, though this may be partially due to translation issues. Despite its flaws, the film offers valuable perspectives on Kurdish experience and shows the potential of Kurdish cinema with better resources and development time.',
            rating: 5,
            isComingSoon: false,
            helpful: 9,
            spoilerWarning: false,
            createdAt: new Date('2024-08-25T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-08-25T16:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 9,
            movieType: 'kurdish',
            title: 'Disappointing Despite Good Intentions',
            content: 'While I appreciate the effort to create Kurdish content and the important cultural themes this film attempts to address, the execution falls short of its ambitions. The story about a Kurdish family navigating modern challenges has merit, but poor pacing and weak character development undermine the narrative. The lead actor seems uncomfortable in the role, delivering lines that feel rehearsed rather than natural. Technical issues plague the production, with inconsistent audio levels and some poorly framed shots that distract from the story. The film tries to cover too many themes without developing any of them sufficiently. Cultural elements feel forced rather than integrated naturally into the narrative. The ending feels rushed and unearned given the character development throughout the film. Kurdish cinema deserves better representation than this well-intentioned but poorly executed effort.',
            rating: 3,
            isComingSoon: false,
            helpful: 7,
            spoilerWarning: false,
            createdAt: new Date('2024-09-10T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-10T11:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 9999,
            movieType: 'coming_soon',
            title: 'High Expectations for Superhero Epic',
            content: 'Based on the trailers and behind-the-scenes footage, this upcoming superhero film looks like it could be a game-changer for the genre. The director previous work demonstrates a strong understanding of character development and visual storytelling. The cast appears well-suited to their roles, particularly the lead who brings both physical presence and dramatic range. The production design seems to create a unique visual identity that distinguishes it from other superhero films. Early reports suggest practical effects are being prioritized over CGI, which could result in more grounded and believable action sequences. The story appears to tackle more mature themes while maintaining the entertainment value expected from the genre. My main concern is whether the film can balance multiple character arcs without feeling overstuffed. If the execution matches the ambition shown in promotional materials, this could be a standout entry in the superhero genre.',
            rating: 8,
            isComingSoon: true,
            helpful: 23,
            spoilerWarning: false,
            createdAt: new Date('2024-10-18T13:25:00Z').toISOString(),
            updatedAt: new Date('2024-10-18T13:25:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 10000,
            movieType: 'coming_soon',
            title: 'Cautiously Optimistic About Horror Sequel',
            content: 'The trailers for this horror sequel show promise, but sequels in this genre are notoriously difficult to execute well. The original film was a surprise hit that relied on atmosphere and character development rather than cheap scares. Early footage suggests the filmmakers understand what made the original work, focusing on psychological tension rather than gore. The returning cast members appear to have maintained their chemistry, which was crucial to the first film success. New additions to the cast seem well-chosen, though their characters remain mysterious from promotional materials. The production values appear higher than the original, which could be either a benefit or a detriment depending on how the increased budget is utilized. My concern is whether the film can recapture the intimate, claustrophobic feeling that made the original so effective. Horror sequels often fall into the trap of simply amplifying what worked before rather than expanding the story meaningfully.',
            rating: 6,
            isComingSoon: true,
            helpful: 15,
            spoilerWarning: false,
            createdAt: new Date('2024-11-05T17:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-05T17:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 10001,
            movieType: 'coming_soon',
            title: 'Concerns About Sci-Fi Adaptation',
            content: 'As a fan of the original source material, I have mixed feelings about this upcoming sci-fi adaptation. The book complex themes and intricate world-building present significant challenges for any film adaptation. While the director has shown skill with character-driven narratives, this project requires a different scale and approach. The casting choices are puzzling - while the actors are talented, they do not seem to match the characters as described in the source material. The trailers suggest significant departures from the book plot, which could work if handled skillfully but risks alienating existing fans. The visual effects look impressive but potentially overwhelming, raising concerns about style over substance. Production reports suggest a troubled development process with multiple script rewrites and reshoots. My fear is that this will be another case of a beloved book being adapted without understanding what made it special. I hope to be proven wrong, but expectations remain low.',
            rating: 4,
            isComingSoon: true,
            helpful: 11,
            spoilerWarning: false,
            createdAt: new Date('2024-11-22T09:50:00Z').toISOString(),
            updatedAt: new Date('2024-11-22T09:50:00Z').toISOString(),
        }
    ];

    await db.insert(movieReviews).values(sampleReviews);
    
    console.log('✅ Movie reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});