import { db } from '@/db';
import { movieReviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 155,
            movieType: 'tmdb',
            title: 'A Dark Knight Masterpiece',
            content: 'Christopher Nolan has outdone himself with The Dark Knight. This film transcends the superhero genre and becomes something much more profound. Heath Ledger\'s portrayal of the Joker is absolutely mesmerizing - every scene he\'s in crackles with unpredictable energy. The way he embodies chaos theory in human form is both terrifying and brilliant. Christian Bale delivers another solid performance as Batman, but it\'s really Ledger who steals the show. The film\'s exploration of moral ambiguity, the thin line between hero and villain, and the cost of doing what\'s right makes this more than just entertainment. The cinematography is stunning, the practical effects feel real and weighty, and Hans Zimmer\'s score perfectly complements the dark tone. This is filmmaking at its finest.',
            rating: 10,
            isComingSoon: false,
            helpful: 15,
            spoilerWarning: false,
            createdAt: new Date('2024-01-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-01-15T14:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 550,
            movieType: 'tmdb',
            title: 'Mind-Bending Cinema at Its Best',
            content: 'Fight Club is one of those rare films that gets better with each viewing. David Fincher\'s direction is meticulous, creating a grimy, underground world that feels both realistic and surreal. Brad Pitt and Edward Norton have incredible chemistry, and their performances carry the psychological weight of the story perfectly. The film\'s critique of consumer culture and masculinity in crisis feels even more relevant today than when it was released. What starts as a seemingly straightforward story about an insomniac finding purpose through underground fighting evolves into something much deeper and more complex. The cinematography uses shadow and light brilliantly to reflect the protagonist\'s mental state. Without giving anything away, the final act completely recontextualizes everything you\'ve seen before. This is essential viewing for anyone who appreciates intelligent, thought-provoking cinema.',
            rating: 9,
            isComingSoon: false,
            helpful: 12,
            spoilerWarning: true,
            createdAt: new Date('2024-01-20T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-01-20T09:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 238,
            movieType: 'tmdb',
            title: 'Timeless Classic That Defines Cinema',
            content: 'The Godfather remains the gold standard for epic storytelling in cinema. Francis Ford Coppola created a masterpiece that works on multiple levels - as a crime drama, a family saga, and a meditation on power and corruption. Marlon Brando\'s Don Vito Corleone is one of the most iconic characters ever put to film, delivered with such nuance and gravitas that every gesture feels significant. The supporting cast, including James Caan, Robert Duvall, and a young Al Pacino, creates a rich ensemble that brings the Corleone family to vivid life. The film\'s pacing is deliberate and methodical, allowing characters and relationships to develop naturally. Gordon Willis\'s cinematography creates a shadowy, intimate world where power operates in whispers and glances. The transformation of Michael Corleone from war hero to ruthless don is one of cinema\'s greatest character arcs. Nearly fifty years later, this film still feels fresh and relevant.',
            rating: 10,
            isComingSoon: false,
            helpful: 8,
            spoilerWarning: false,
            createdAt: new Date('2024-01-25T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-01-25T16:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 27205,
            movieType: 'tmdb',
            title: 'Nolan\'s Most Ambitious Project Yet',
            content: 'Inception is Christopher Nolan at his most ambitious and creative. The concept of dreams within dreams creates a layered narrative structure that rewards careful attention and multiple viewings. Leonardo DiCaprio anchors the film with a performance that balances the technical exposition with genuine emotional weight. The supporting ensemble, including Marion Cotillard, Tom Hardy, and Ellen Page, each brings distinct personalities to their specialized roles. What impresses me most is how Nolan makes the complex rules of dream logic feel consistent and believable within the film\'s universe. The action sequences are innovative, particularly the rotating hallway fight and the zero-gravity hotel scenes. Hans Zimmer\'s score uses the famous "BRAAAM" sound to great effect, creating tension and disorientation. The film asks profound questions about reality, memory, and guilt while delivering spectacular entertainment. The ending is perfect in its ambiguity, leaving viewers to draw their own conclusions about what\'s real.',
            rating: 9,
            isComingSoon: false,
            helpful: 11,
            spoilerWarning: true,
            createdAt: new Date('2024-02-01T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-01T11:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 680,
            movieType: 'tmdb',
            title: 'Pulp Fiction: Revolutionary Storytelling',
            content: 'Quentin Tarantino\'s Pulp Fiction revolutionized cinema with its non-linear narrative structure and razor-sharp dialogue. The film weaves together multiple storylines in Los Angeles\' criminal underworld, creating a tapestry that\'s both stylized and grittily realistic. John Travolta and Samuel L. Jackson have incredible chemistry as Vincent Vega and Jules Winnfield, delivering Tarantino\'s distinctive dialogue with perfect timing and rhythm. Uma Thurman\'s Mia Wallace is captivating, bringing both vulnerability and danger to her scenes with Travolta. The film\'s structure, jumping between different time periods, keeps viewers engaged and constantly surprised. Each segment has its own tone and energy while contributing to the larger whole. The soundtrack perfectly captures the film\'s retro-cool aesthetic. Tarantino\'s direction balances extreme violence with dark comedy, creating a unique viewing experience that influenced countless filmmakers. This is essential cinema that redefined what popular movies could be.',
            rating: 9,
            isComingSoon: false,
            helpful: 7,
            spoilerWarning: false,
            createdAt: new Date('2024-02-05T13:10:00Z').toISOString(),
            updatedAt: new Date('2024-02-05T13:10:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 1,
            movieType: 'kurdish',
            title: 'Beautiful Kurdish Cinema',
            content: 'This Kurdish film represents the best of contemporary Middle Eastern cinema. The story follows a family struggling with tradition and modernity in the changing landscape of Kurdistan. The performances feel authentic and lived-in, with the lead actors bringing genuine emotion to their roles. What strikes me most is the film\'s visual poetry - the cinematographer captures the natural beauty of Kurdistan while also showing the harsh realities of everyday life. The director doesn\'t shy away from complex political and social issues, but handles them with nuance rather than heavy-handed messaging. The pacing is contemplative, allowing moments to breathe and characters to develop naturally. The use of Kurdish music and traditional songs adds layers of cultural authenticity. The film explores themes of displacement, identity, and hope with remarkable sensitivity. For viewers unfamiliar with Kurdish culture, this serves as both entertainment and education. This is the kind of filmmaking that builds bridges between cultures while telling a deeply personal story.',
            rating: 8,
            isComingSoon: false,
            helpful: 6,
            spoilerWarning: false,
            createdAt: new Date('2024-02-08T15:30:00Z').toISOString(),
            updatedAt: new Date('2024-02-08T15:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 2,
            movieType: 'kurdish',
            title: 'Promising But Flawed',
            content: 'This Kurdish drama has moments of genuine brilliance but suffers from pacing issues that prevent it from reaching its full potential. The central performance is strong, with the lead actor conveying deep emotion through subtle facial expressions and body language. The story tackles important themes about family honor and personal freedom, particularly for young women in traditional Kurdish society. However, the film\'s middle section drags considerably, with several scenes that feel repetitive rather than building tension or character development. The cinematography is generally good, capturing both intimate family moments and sweeping landscape shots effectively. The supporting cast varies in quality, with some actors delivering naturalistic performances while others feel stiff and unconvincing. The film\'s ending is powerful and emotionally satisfying, which somewhat redeems the slower middle section. Despite its flaws, this movie represents an important voice in Kurdish cinema and tackles subjects that need more representation on screen. With tighter editing and stronger supporting performances, this could have been exceptional.',
            rating: 6,
            isComingSoon: false,
            helpful: 4,
            spoilerWarning: false,
            createdAt: new Date('2024-02-12T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-02-12T10:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 3,
            movieType: 'coming_soon',
            title: 'High Expectations for This Upcoming Kurdish Epic',
            content: 'Based on the trailers and behind-the-scenes footage, this upcoming Kurdish historical epic looks incredibly promising. The production values appear significantly higher than most regional cinema, with elaborate period costumes and impressive battle sequences. The director has assembled an international cast while keeping the story rooted in authentic Kurdish history and culture. What excites me most is the film\'s apparent commitment to historical accuracy while still delivering spectacular entertainment. The cinematography showcased in the trailers suggests sweeping scope and intimate character moments. Early reports indicate the film will be released with Kurdish, Arabic, and English audio options, potentially reaching a much wider audience than typical Kurdish productions. The story reportedly follows a legendary Kurdish warrior during a pivotal historical period, combining personal drama with larger political themes. If the final product lives up to the promotional material, this could be a breakthrough moment for Kurdish cinema on the international stage. The production has taken several years, suggesting careful attention to detail and quality.',
            rating: 8,
            isComingSoon: true,
            helpful: 3,
            spoilerWarning: false,
            createdAt: new Date('2024-02-15T12:20:00Z').toISOString(),
            updatedAt: new Date('2024-02-15T12:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 4,
            movieType: 'coming_soon',
            title: 'Marvel\'s Next Phase Looks Incredible',
            content: 'The trailer for this upcoming Marvel film has me more excited than I\'ve been for a superhero movie in years. After some recent disappointments in the MCU, this appears to return to the character-driven storytelling that made the early phases so compelling. The visual effects look stunning, but more importantly, the emotional stakes seem genuine and personal rather than just world-ending spectacle. The casting choices are inspired, particularly the lead actor who brings both physicality and vulnerability to the role. What\'s most encouraging is how the film appears to balance humor with serious themes, avoiding the quip-heavy tone that has plagued some recent Marvel entries. The action sequences shown in trailers suggest creative choreography and practical stunts mixed with CGI enhancement. Early test screening reports have been overwhelmingly positive, with particular praise for the film\'s third act and character development. If this delivers on its promises, it could revitalize the MCU and set up exciting future storylines. The director\'s previous work gives me confidence in their ability to handle both intimate character moments and large-scale action.',
            rating: 7,
            isComingSoon: true,
            helpful: 9,
            spoilerWarning: false,
            createdAt: new Date('2024-02-18T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-02-18T14:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            movieId: 5,
            movieType: 'tmdb',
            title: 'Disappointing Despite Great Potential',
            content: 'This film had all the ingredients for success but somehow fails to come together in a satisfying way. The premise is intriguing and the cast is talented, but the script lets everyone down with inconsistent character motivations and plot holes you could drive a truck through. The first act shows real promise, establishing an interesting world and compelling characters, but the momentum completely stalls in the second act with unnecessary subplots and repetitive dialogue. The lead performance is committed but can\'t overcome the material\'s fundamental weaknesses. The supporting cast seems confused about what kind of movie they\'re in, with some playing things deadly serious while others go for broad comedy. The cinematography is competent but uninspired, failing to create any distinctive visual identity. The film\'s biggest sin is wasting its talented ensemble on a story that never figures out what it wants to be. By the time the climax arrives, any goodwill from the promising opening has been completely squandered. This feels like a first draft that somehow made it to production.',
            rating: 4,
            isComingSoon: false,
            helpful: 2,
            spoilerWarning: true,
            createdAt: new Date('2024-02-20T16:50:00Z').toISOString(),
            updatedAt: new Date('2024-02-20T16:50:00Z').toISOString(),
        }
    ];

    await db.insert(movieReviews).values(sampleReviews);
    
    console.log('✅ Movie reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});