import { db } from '@/db';
import { tvShows } from '@/db/schema';

async function main() {
    const sampleTvShows = [
        // Netflix shows (6)
        {
            tmdbId: 66732,
            name: 'Stranger Things',
            nameKurdish: 'شتە سەیرەکان',
            overview: 'When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces, and one strange little girl.',
            overviewKurdish: 'کاتێک کوڕێکی گەنج ون دەبێت، شارۆچکەیەک نهێنییەک دەردەخات کە تاقیکردنەوە نهێنییەکان، هێزە سامناکە سەرووسروشتییەکان، و کچێکی بچووک و سەیرەو لەخۆدەگرێت.',
            posterPath: '/x2LSRK2Cm7MZhjluni1msVJ3wDF.jpg',
            backdropPath: '/56v2KjBlU4XaOv9rVYEQypROD7P.jpg',
            firstAirDate: '2016-07-15',
            voteAverage: 8.6,
            genreIds: JSON.stringify([18, 10765, 9648]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 4,
            totalEpisodes: 42,
            status: 'ongoing',
            createdAt: new Date('2024-01-15').toISOString(),
            updatedAt: new Date('2024-01-15').toISOString(),
        },
        {
            tmdbId: 1396,
            name: 'Breaking Bad',
            nameKurdish: 'شکاندنی خراپ',
            overview: 'A high school chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine in order to secure his family\'s future.',
            overviewKurdish: 'مامۆستایەکی کیمیای ئامادەیی کە تووشی شێرپەنجەی سییەکان بووە، ڕووی لە دروستکردن و فرۆشتنی میتامفیتامین دەکات بۆ دابینکردنی داهاتووی خێزانەکەی.',
            posterPath: '/3xnWaLQjelJDDF7LT1WBo6f4BRe.jpg',
            backdropPath: '/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
            firstAirDate: '2008-01-20',
            voteAverage: 9.5,
            genreIds: JSON.stringify([18, 80]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 5,
            totalEpisodes: 62,
            status: 'completed',
            createdAt: new Date('2024-01-10').toISOString(),
            updatedAt: new Date('2024-01-10').toISOString(),
        },
        {
            tmdbId: 70523,
            name: 'Dark',
            nameKurdish: 'تاریکی',
            overview: 'A family saga with a supernatural twist, set in a German town, where the disappearance of two young children exposes the relationships among four families.',
            overviewKurdish: 'چیرۆکێکی خێزانی لەگەڵ پێچ و گرێیەکی سەرووسروشتی، لە شارۆچکەیەکی ئەڵمانیدا ڕوودەدات، کە ونبوونی دوو منداڵی گەنج پەیوەندییەکانی نێوان چوار خێزان ئاشکرا دەکات.',
            posterPath: '/apbrbWs8M9lyOpJYU5WXrpFbk1Z.jpg',
            backdropPath: '/5wjFt58U5905K9cNUnfWEBXlu0I.jpg',
            firstAirDate: '2017-12-01',
            voteAverage: 8.8,
            genreIds: JSON.stringify([18, 10765, 9648]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 3,
            totalEpisodes: 26,
            status: 'completed',
            createdAt: new Date('2024-01-12').toISOString(),
            updatedAt: new Date('2024-01-12').toISOString(),
        },
        {
            tmdbId: 4026,
            name: 'The Crown',
            nameKurdish: 'تاج',
            overview: 'Follows the political rivalries and romance of Queen Elizabeth II\'s reign and the events that shaped the second half of the twentieth century.',
            overviewKurdish: 'شوێن ڕکابەرییە سیاسییەکان و عاشقانەکانی پاشایەتی شاژن ئەلیزابێسی دووەم و ڕووداوەکانی کە نیوەی دووەمی سەدەی بیستەمیان شێوەپێدا.',
            posterPath: '/1M876KPjulVwppEpldhdc8V4o68.jpg',
            backdropPath: '/8z7DSqxaNjNiL9PQzb6bKmKQzQj.jpg',
            firstAirDate: '2016-11-04',
            voteAverage: 8.2,
            genreIds: JSON.stringify([18, 36]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 6,
            totalEpisodes: 60,
            status: 'ongoing',
            createdAt: new Date('2024-01-14').toISOString(),
            updatedAt: new Date('2024-01-14').toISOString(),
        },
        {
            tmdbId: 119051,
            name: 'Wednesday',
            nameKurdish: 'چوارشەممە',
            overview: 'Smart, sarcastic and a little dead inside, Wednesday Addams investigates a murder spree while making new friends — and foes — at Nevermore Academy.',
            overviewKurdish: 'زیرەک و قسەتاڵ و کەمێک لە ناوەوە مردوو، چوارشەممە ئادامز لیکۆڵینەوە لە زنجیرەیەک کوشتن دەکات لە کاتێکدا هاوڕێی نوێ و دوژمن لە زانکۆی نێڤەرمۆر دروست دەکات.',
            posterPath: '/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
            backdropPath: '/iHSwvRVsRyxpX7FE7GbviaDvgGZ.jpg',
            firstAirDate: '2022-11-23',
            voteAverage: 8.4,
            genreIds: JSON.stringify([35, 80, 9648]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 2,
            totalEpisodes: 16,
            status: 'ongoing',
            createdAt: new Date('2024-01-16').toISOString(),
            updatedAt: new Date('2024-01-16').toISOString(),
        },
        {
            tmdbId: 58623,
            name: 'Emily in Paris',
            nameKurdish: 'ئیمیلی لە پاریس',
            overview: 'When ambitious Chicago marketing exec Emily Cooper is unexpectedly transferred to Paris, she embraces a new life as she juggles work, friends and romance.',
            overviewKurdish: 'کاتێک ئیمیلی کووپەری جێبەجێکاری بازرگانی شیکاگۆ بە نەخوازراوی گوازرایەوە بۆ پاریس، ژیانێکی نوێ قبوڵ دەکات کە کار و هاوڕێیان و عاشقانە تێکەڵ دەکات.',
            posterPath: '/3rftbNb1VKUsoOdyWR7C10gNJq7.jpg',
            backdropPath: '/cHMakmGSodTLZ8eO4FvPVH49dQF.jpg',
            firstAirDate: '2020-10-02',
            voteAverage: 7.0,
            genreIds: JSON.stringify([35, 18]),
            streamingService: 'netflix',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 3,
            totalEpisodes: 30,
            status: 'ongoing',
            createdAt: new Date('2024-01-18').toISOString(),
            updatedAt: new Date('2024-01-18').toISOString(),
        },
        // Disney+ shows (5)
        {
            tmdbId: 82856,
            name: 'The Mandalorian',
            nameKurdish: 'مەندەلۆریان',
            overview: 'After the fall of the Galactic Empire, lawlessness has spread throughout the galaxy. A lone gunfighter makes his way through the outer reaches of the galaxy.',
            overviewKurdish: 'دوای کەوتنی ئیمپراتۆریەتی گەلاکسی، یاساشکێنی بە سەرانسەری گەلاکسیدا بڵاوبووەتەوە. جەنگاوەرێکی تەنها ڕێگای خۆی بە لەتەکانی دووری گەلاکسیدا دەکات.',
            posterPath: '/sWgBv7LV2PRoQgkxwlibdGXKz1S.jpg',
            backdropPath: '/o7qi2v4uWQ8bZ1OvC7y8F7gGhH2.jpg',
            firstAirDate: '2019-11-12',
            voteAverage: 8.5,
            genreIds: JSON.stringify([10759, 18, 10765]),
            streamingService: 'disney',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 3,
            totalEpisodes: 24,
            status: 'ongoing',
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            tmdbId: 85271,
            name: 'WandaVision',
            nameKurdish: 'وەندەڤیژن',
            overview: 'Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.',
            overviewKurdish: 'وەندە مەکسیمۆف و ڤیژن - دوو بوونەوەری سووپەر هێز کە ژیانی خانەنشینی ئایدیاڵ دەژین - دەست دەکەن بە گومانکردن کە هەموو شت وەک دیارە نییە.',
            posterPath: '/glKDfE6btIRcVB5zrjspRIs4r52.jpg',
            backdropPath: '/57vVjteucIF3bGnZj6PmaoJRScw.jpg',
            firstAirDate: '2021-01-15',
            voteAverage: 8.2,
            genreIds: JSON.stringify([18, 10765, 9648]),
            streamingService: 'disney',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 1,
            totalEpisodes: 9,
            status: 'completed',
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            tmdbId: 84958,
            name: 'Loki',
            nameKurdish: 'لۆکی',
            overview: 'After stealing the Tesseract during the events of "Avengers: Endgame," an alternate version of Loki is brought to the Time Variance Authority.',
            overviewKurdish: 'دوای دزینی تێسەرەکت لە کاتی ڕووداوەکانی "ئەڤێنجەرز: کۆتایی یاری"، وەشانێکی جیاوازی لۆکی بۆ ڕێکخراوی جیاوازی کات دەهێنرێت.',
            posterPath: '/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg',
            backdropPath: '/kqjL17yufvn9OVLyXYpvtyrFfak.jpg',
            firstAirDate: '2021-06-09',
            voteAverage: 8.1,
            genreIds: JSON.stringify([18, 10765, 35]),
            streamingService: 'disney',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 2,
            totalEpisodes: 12,
            status: 'ongoing',
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            tmdbId: 456,
            name: 'The Simpsons',
            nameKurdish: 'سیمپسۆنەکان',
            overview: 'Set in Springfield, the average American town, the show focuses on the antics and everyday adventures of the Simpson family.',
            overviewKurdish: 'لە سپرینگفیلد دانراوە، شارۆچکە ئاسایی ئەمریکییەکە، برنامەکە سەرنج دەداتە سەر کردەوە خۆشەکان و سەرگەرمییە ڕۆژانەکانی خێزانی سیمپسۆن.',
            posterPath: '/zLudbPueg8CxGhMS2tyDh3p0TdK.jpg',
            backdropPath: '/f5uNbUC76oowt5mt5J9QlqrIZjq.jpg',
            firstAirDate: '1989-12-17',
            voteAverage: 8.0,
            genreIds: JSON.stringify([16, 35, 10751]),
            streamingService: 'disney',
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            totalSeasons: 35,
            totalEpisodes: 750,
            status: 'ongoing',
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            tmdbId: 91759,
            name: 'High School Musical: The Musical: The Series',
            nameKurdish: 'میوزیکاڵی قوتابخانەی ئامادەیی: میوزیکاڵ: زنجیرەکە',
            overview: 'A mockumentary following the lives of students at East High who stage a musical production of "High School Musical."',
            overviewKurdish: 'بەڵگەنامەیەکی گاڵتەجاڕ کە شوێن ژیانی خوێندکارانی قوتابخانەی ڕۆژهەڵاتی دەکات کە پێشکەشکردنی میوزیکاڵی "میوزیکاڵی قوتابخانەی ئامادەیی" ئەنجام دەدەن.',
            posterPath: '/2dXkNM3k4jXGeaOjW50cUjGiKF6.jpg',
            backdropPath: '/1q7kICp8G6DKCEYrKRNGa4nZd8c.jpg',
            firstAirDate: '2019-11-08',
            voteAverage: 7.8,
            genreIds: JSON.stringify([35, 18, 10751]),
            streamingService: 'disney',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 4,
            totalEpisodes: 38,
            status: 'ongoing',
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        // Amazon Prime shows (5)
        {
            tmdbId: 76479,
            name: 'The Boys',
            nameKurdish: 'کوڕەکان',
            overview: 'A group of vigilantes set out to take down corrupt superheroes with no more than blue-collar grit and a willingness to fight dirty.',
            overviewKurdish: 'گروپێک لە چاودێران دەیانهەوێت سووپەرهیرۆ گەندەڵەکان لەناوببەن بەبێ هیچ شتێک جگە لە پاڵەوانی کرێکار و ئامادەیی بۆ جەنگی پیس.',
            posterPath: '/mY7SeH4HFFxW1hiI6cWuwCRKptN.jpg',
            backdropPath: '/8VQ6GcAg1GZFcGAgDjIAUq0EfNx.jpg',
            firstAirDate: '2019-07-26',
            voteAverage: 8.7,
            genreIds: JSON.stringify([10759, 35, 18]),
            streamingService: 'prime',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 4,
            totalEpisodes: 32,
            status: 'ongoing',
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            tmdbId: 70796,
            name: 'The Marvelous Mrs. Maisel',
            nameKurdish: 'خاتوو مایسەلی سەرسوڕهێنەر',
            overview: 'A housewife in 1958 decides to become a stand-up comic.',
            overviewKurdish: 'خانمێکی ماڵەوە لە ساڵی ١٩٥٨ بڕیار دەدات ببێتە کۆمیدیانی وەستاو.',
            posterPath: '/zS7fQiOZiKCVH2vlYSiIsFWW8hh.jpg',
            backdropPath: '/jbTqUzi7cNIHZJoyPKWnBvdBnAs.jpg',
            firstAirDate: '2017-03-17',
            voteAverage: 8.5,
            genreIds: JSON.stringify([35, 18]),
            streamingService: 'prime',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 5,
            totalEpisodes: 43,
            status: 'completed',
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            tmdbId: 90462,
            name: 'Reacher',
            nameKurdish: 'ڕیچەر',
            overview: 'Jack Reacher, a veteran military police investigator, has just recently entered civilian life.',
            overviewKurdish: 'جاک ڕیچەر، لێکۆڵەری کۆنی پۆلیسی سەربازی، تازەگی چووەتە ژیانی مەدەنی.',
            posterPath: '/A6kPSAMK7sQUCZIIvnUJOI7EAOH.jpg',
            backdropPath: '/gUmRSZRlWOzFhZikDNHwYtWVNjR.jpg',
            firstAirDate: '2022-02-04',
            voteAverage: 8.0,
            genreIds: JSON.stringify([10759, 80, 18]),
            streamingService: 'prime',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 2,
            totalEpisodes: 16,
            status: 'ongoing',
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            tmdbId: 67338,
            name: 'The Grand Tour',
            nameKurdish: 'گەشتی گەورە',
            overview: 'Jeremy Clarkson, Richard Hammond and James May are back with a show about adventure, excitement and friendship.',
            overviewKurdish: 'جێرەمی کلارکسۆن، ڕیچارد هەممۆند و جەیمس مەی گەڕاونەتەوە لەگەڵ پڕۆگرامێک دەربارەی سەرگەرمی، هەڵچوون و هاوڕێیەتی.',
            posterPath: '/6Mm5H2bjhyC4KpWKOJc8zKrk2bT.jpg',
            backdropPath: '/oMlHDnP37iqSlvRSGxpk6eUZJIL.jpg',
            firstAirDate: '2016-11-18',
            voteAverage: 8.2,
            genreIds: JSON.stringify([99, 10751]),
            streamingService: 'prime',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 5,
            totalEpisodes: 45,
            status: 'ongoing',
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            tmdbId: 95557,
            name: 'Invincible',
            nameKurdish: 'شکستناپذیر',
            overview: 'Mark Grayson is a normal teenager except for the fact that his father is the most powerful superhero on the planet.',
            overviewKurdish: 'مارک گرەیسۆن لاوێکی ئاسایی نۆبارەیە جگە لەوەی کە باوکی بەهێزترین سووپەرهیرۆی سەروی زەوییە.',
            posterPath: '/yDWJYRAwMNKbIYT8ZB33qy84uzO.jpg',
            backdropPath: '/6UH52Fmau8RPsMAbQbjwN3wJSCj.jpg',
            firstAirDate: '2021-03-26',
            voteAverage: 8.6,
            genreIds: JSON.stringify([16, 10759, 18]),
            streamingService: 'prime',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 2,
            totalEpisodes: 16,
            status: 'ongoing',
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        // Other services (4)
        {
            tmdbId: 94997,
            name: 'House of the Dragon',
            nameKurdish: 'ماڵی ئەژدیها',
            overview: 'The Targaryen civil war begins. Based on George R.R. Martin\'s "Fire & Blood," the series, set 200 years before "Game of Thrones."',
            overviewKurdish: 'شەڕی ناوخۆیی تارگاریەنەکان دەست پێدەکات. لەسەر بنەمای "ئاگر و خوێن"ی جۆرج ئار.ئار. مارتن، زنجیرەکە ٢٠٠ساڵ پێش "یارییەکانی تەخت" ڕوودەدات.',
            posterPath: '/7QMsOTMUswlwxJP0rTTZfmz2tX2.jpg',
            backdropPath: '/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg',
            firstAirDate: '2022-08-21',
            voteAverage: 8.4,
            genreIds: JSON.stringify([18, 10759, 10765]),
            streamingService: 'hbo',
            hasKurdishDub: false,
            hasKurdishSubtitle: true,
            totalSeasons: 2,
            totalEpisodes: 18,
            status: 'completed',
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            tmdbId: 97546,
            name: 'Ted Lasso',
            nameKurdish: 'تێد لاسۆ',
            overview: 'Ted Lasso, an American football coach, moves to England when he\'s hired to coach a soccer team—despite having no experience coaching soccer.',
            overviewKurdish: 'تێد لاسۆ، ڕاهێنەری تۆپی پێی ئەمریکی، دەچێتە ئینگلتەرا کاتێک بۆ ڕاهێنانی تیمێکی تۆپی پێ بەکرێ دەگیرێت - سەرەڕای ئەوەی هیچ ئەزموونێکی لە ڕاهێنانی تۆپی پێدا نییە.',
            posterPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg',
            backdropPath: '/5fhZdwP1DVJ0FyVH6vrFdHwpXIn.jpg',
            firstAirDate: '2020-08-14',
            voteAverage: 8.8,
            genreIds: JSON.stringify([35, 18]),
            streamingService: 'appletv',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 3,
            totalEpisodes: 34,
            status: 'completed',
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            tmdbId: 67741,
            name: 'Succession',
            nameKurdish: 'دوایی',
            overview: 'The Roy family is known for controlling the biggest media and entertainment company in the world.',
            overviewKurdish: 'خێزانی ڕۆی بەوەوە ناسراون کە گەورەترین کۆمپانیای میدیا و کەلتوور لە جیهاندا کۆنترۆڵ دەکەن.',
            posterPath: '/7HW47XbkNQ5fiwQFYGWdw9gs144.jpg',
            backdropPath: '/jGHdkd0PQrOWZcPvIjKpB3qpFvQ.jpg',
            firstAirDate: '2018-06-03',
            voteAverage: 8.3,
            genreIds: JSON.stringify([18, 35]),
            streamingService: 'hbo',
            hasKurdishDub: false,
            hasKurdishSubtitle: false,
            totalSeasons: 4,
            totalEpisodes: 39,
            status: 'cancelled',
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            tmdbId: 1668,
            name: 'Yellowstone',
            nameKurdish: 'یێلۆستۆن',
            overview: 'Follow the violent world of the Dutton family, who controls the largest contiguous ranch in the United States.',
            overviewKurdish: 'شوێن جیهانی توندوتیژی خێزانی داتۆن بکە، کە گەورەترین ڕانچی پێکەوەبەستراوی ویلایەتە یەکگرتووەکان کۆنترۆڵ دەکەن.',
            posterPath: '/peNC0CP27TebtdydQw2r0mH9tLw.jpg',
            backdropPath: '/5CGjvTFb4uB8dn3Kaby9dJQnfpC.jpg',
            firstAirDate: '2018-06-20',
            voteAverage: 8.0,
            genreIds: JSON.stringify([18, 37]),
            streamingService: 'paramount',
            hasKurdishDub: true,
            hasKurdishSubtitle: true,
            totalSeasons: 5,
            totalEpisodes: 47,
            status: 'cancelled',
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
    ];

    await db.insert(tvShows).values(sampleTvShows);
    
    console.log('✅ TV Shows seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});