import { db } from '@/db';
import { userAchievements } from '@/db/schema';

async function main() {
    const sampleAchievements = [
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'first_review',
            achievementName: 'First Review',
            achievementDescription: 'Write your first movie review',
            progress: 1,
            target: 1,
            isCompleted: true,
            completedAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:star-outline.svg',
            points: 10,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-08-15T14:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'movie_critic',
            achievementName: 'Movie Critic',
            achievementDescription: 'Write 10 movie reviews',
            progress: 10,
            target: 10,
            isCompleted: true,
            completedAt: new Date('2024-09-20T16:45:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:movie-edit-outline.svg',
            points: 50,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-20T16:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'movie_critic',
            achievementName: 'Seasoned Critic',
            achievementDescription: 'Write 25 movie reviews',
            progress: 23,
            target: 25,
            isCompleted: false,
            completedAt: null,
            iconUrl: 'https://api.iconify.design/mdi:movie-star.svg',
            points: 100,
            createdAt: new Date('2024-09-20T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T18:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'popular_reviewer',
            achievementName: 'Rising Star',
            achievementDescription: 'Receive 10 helpful votes on your reviews',
            progress: 10,
            target: 10,
            isCompleted: true,
            completedAt: new Date('2024-10-05T12:15:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:thumb-up-outline.svg',
            points: 30,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-05T12:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'popular_reviewer',
            achievementName: 'Community Favorite',
            achievementDescription: 'Receive 50 helpful votes on your reviews',
            progress: 52,
            target: 50,
            isCompleted: true,
            completedAt: new Date('2024-11-18T14:30:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:heart-multiple.svg',
            points: 75,
            createdAt: new Date('2024-10-05T12:15:00Z').toISOString(),
            updatedAt: new Date('2024-11-18T14:30:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'prolific_commenter',
            achievementName: 'Active Discussant',
            achievementDescription: 'Post 25 comments on movie reviews',
            progress: 25,
            target: 25,
            isCompleted: true,
            completedAt: new Date('2024-10-28T19:45:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:comment-multiple-outline.svg',
            points: 40,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-10-28T19:45:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'prolific_commenter',
            achievementName: 'Discussion Leader',
            achievementDescription: 'Post 100 comments on movie reviews',
            progress: 37,
            target: 100,
            isCompleted: false,
            completedAt: null,
            iconUrl: 'https://api.iconify.design/mdi:account-voice.svg',
            points: 150,
            createdAt: new Date('2024-10-28T19:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T20:15:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'helpful_reviewer',
            achievementName: 'Helpful Insights',
            achievementDescription: 'Have 5 of your reviews marked as helpful',
            progress: 5,
            target: 5,
            isCompleted: true,
            completedAt: new Date('2024-09-12T11:20:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:lightbulb-outline.svg',
            points: 25,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-09-12T11:20:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'helpful_reviewer',
            achievementName: 'Expert Reviewer',
            achievementDescription: 'Have 20 of your reviews marked as helpful',
            progress: 17,
            target: 20,
            isCompleted: false,
            completedAt: null,
            iconUrl: 'https://api.iconify.design/mdi:certificate-outline.svg',
            points: 100,
            createdAt: new Date('2024-09-12T11:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T16:40:00Z').toISOString(),
        },
        {
            userId: 'user_2mQJ8k3L9pN4R7tS8vW1x',
            achievementType: 'early_adopter',
            achievementName: 'Movie Scout',
            achievementDescription: 'Review 5 coming soon movies',
            progress: 5,
            target: 5,
            isCompleted: true,
            completedAt: new Date('2024-11-25T13:10:00Z').toISOString(),
            iconUrl: 'https://api.iconify.design/mdi:telescope.svg',
            points: 60,
            createdAt: new Date('2024-08-15T14:30:00Z').toISOString(),
            updatedAt: new Date('2024-11-25T13:10:00Z').toISOString(),
        }
    ];

    await db.insert(userAchievements).values(sampleAchievements);
    
    console.log('✅ User achievements seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});